### PR TITLE
Graphviz support

### PR DESCRIPTION
**Pull request by hermanzdosilovic**
Hey @nicbou,

I have added [Graphviz](http://www.graphviz.org/) support using [viz.js](https://github.com/mdaines/viz.js).

Please take a look at `templates/notes/getting_started.md`

Best regards,
Herman

### CODE REVIEW

**Comment by nicbou** [comment]
I will have to test this one, but I believe this is a fantastic addition. To think I used to draw those manually, then import the screenshot...

**Comment by hermanzdosilovic** [comment]
I tested a bit further and it seems that `Viz()` is throwing an error when it can't parse given string. We should catch that error and render appropriate message in that block. Example of this procedure is done [here](http://mdaines.github.io/viz.js/). Hopefully I will update my PR with this feature by end of this week.

**Comment by AuHau** [comment]
Hmm there could be actually easier way of implementing this and through tool called [mermaid](http://knsv.github.io/mermaid/index.html), which is actually based on markdown-like notation and can be easily integrated with marked.js

**Comment by nicbou** [comment]
In any case, I would opt for an already popular solution. Markdown and LaTeX are very well-known already, and a third or fourth addition should be equally popular. 

Alternatively, we could consider supporting embeddable content, including graphs from some popular tool.

**Pull request closed without merging**
